import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

function TopNav() {
  return (
    <nav className="bg-gray-800 text-white p-4">
      <div className="container mx-auto flex justify-between">
        <div className="flex items-center">
          <a href="/" className="mr-4">
            Gallery
          </a>
          <a href="/about">About</a>
        </div>
        <div>
          <a href="/login">Login</a>
        </div>
      </div>
    </nav>
  );
}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="flex-col gap-4 ">
        <TopNav />
        {children}
      </body>
    </html>
  );
}
